// ─────────────────────────────────────────────
// OODA — Core Type Definitions (Client-Centric)
// ─────────────────────────────────────────────

// ── Navigation ────────────────────────────────
export type TabId = 'dashboard' | 'activity' | 'comparison' | 'assistant' | 'profile';

// ── Onboarding ────────────────────────────────
export interface CompanyProfile {
  name: string;
  description: string;
  industry: string;
  location: string;
  website: string;
  targetAudience: string;
  businessType: string;
  primaryGoal: string;
}

export interface Competitor {
  id: string;
  name: string;       // display name / domain
  url: string;        // website or API endpoint
  addedAt: string;    // ISO timestamp
}

export interface OnboardingState {
  completed: boolean;
  currentStep: number; // 1 or 2
}

// ── Auth ──────────────────────────────────────
export interface AuthState {
  isAuthenticated: boolean;
}

// ── Activity Feed (replaces Signals) ─────────
export type ActivityPriority = 'low' | 'medium' | 'high' | 'critical';

export interface ActivityItem {
  id: string;
  competitor: string;
  action: string;          // plain English summary e.g. "updated their pricing"
  detail?: string;         // optional one-liner context
  timestamp: string;
  priority: ActivityPriority;
  isRead?: boolean;
}

// ── Dashboard ─────────────────────────────────
export interface DashboardSummary {
  headline: string;                  // "Everything is stable today."
  recommendation: string;            // "Consider reviewing your retention strategy."
  priority: ActivityPriority;
  marketStatus: 'stable' | 'active' | 'alert';
}

// ── AI Chat ───────────────────────────────────
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

// ── Real Data Models (Replaces Mock Data) ─────
export interface Report {
  companyId: string;    // 'own' or competitor URL/ID
  sourceUrl: string;
  generatedAt: string;  // ISO timestamp
  summary: string;
  pricing: string;
  positioning: string;
  features: string;
  messaging: string;
  strengths: string;
  weaknesses: string;
  recommendations: string;
  rawScrapedData?: string;
  customData?: Record<string, string>;
}

export type SignalSeverity = 'low' | 'medium' | 'high' | 'critical';

export interface Signal {
  id: string;
  type: string;             // e.g. 'Pricing Change', 'Feature Update'
  severity: SignalSeverity;
  description: string;
  previousValue: string;
  currentValue: string;
  timestamp: string;        // ISO timestamp
  competitorId: string;
  competitorName: string;
  analysisVerdict?: string; // The markdown analytical report generated by the reviewer
}

export interface ComparisonResult {
  changed: boolean;
  changes: {
    category: string;
    description: string;
    previousValue: string;
    currentValue: string;
    severity: SignalSeverity;
  }[];
}

export interface ActivityLog {
  id: string;
  type: 'report_generated' | 'report_updated' | 'signal_created' | 'discussion_completed';
  title: string;
  description: string;
  timestamp: string;
  competitorId?: string;
  signalId?: string;
}
