export interface EnvVars {
  EXPO_PUBLIC_OLLAMA_BASE_URL: string | undefined;
  EXPO_PUBLIC_OLLAMA_GENERATE_ENDPOINT: string | undefined;
  EXPO_PUBLIC_OLLAMA_TAGS_ENDPOINT: string | undefined;
  EXPO_PUBLIC_DEFAULT_TIMEOUT: string | undefined;
  EXPO_PUBLIC_DEFAULT_PROVIDER: string | undefined;
  EXPO_PUBLIC_ENABLE_DEBUG: string | undefined;
  EXPO_PUBLIC_MAX_DISCUSSION_ROUNDS: string | undefined;
  EXPO_PUBLIC_MAX_ACTIVE_AGENTS: string | undefined;
  EXPO_PUBLIC_SCRAPER_BASE_URL: string | undefined;
  EXPO_PUBLIC_SCRAPER_ENDPOINT: string | undefined;
  EXPO_PUBLIC_SCRAPER_INTERVAL_HOURS: string | undefined;
  EXPO_PUBLIC_ENABLE_AUTO_SCRAPER: string | undefined;
  EXPO_PUBLIC_REQUEST_TIMEOUT: string | undefined;
}

export const env: EnvVars = {
  EXPO_PUBLIC_OLLAMA_BASE_URL: process.env.EXPO_PUBLIC_OLLAMA_BASE_URL,
  EXPO_PUBLIC_OLLAMA_GENERATE_ENDPOINT: process.env.EXPO_PUBLIC_OLLAMA_GENERATE_ENDPOINT,
  EXPO_PUBLIC_OLLAMA_TAGS_ENDPOINT: process.env.EXPO_PUBLIC_OLLAMA_TAGS_ENDPOINT,
  EXPO_PUBLIC_DEFAULT_TIMEOUT: process.env.EXPO_PUBLIC_DEFAULT_TIMEOUT,
  EXPO_PUBLIC_DEFAULT_PROVIDER: process.env.EXPO_PUBLIC_DEFAULT_PROVIDER,
  EXPO_PUBLIC_ENABLE_DEBUG: process.env.EXPO_PUBLIC_ENABLE_DEBUG,
  EXPO_PUBLIC_MAX_DISCUSSION_ROUNDS: process.env.EXPO_PUBLIC_MAX_DISCUSSION_ROUNDS,
  EXPO_PUBLIC_MAX_ACTIVE_AGENTS: process.env.EXPO_PUBLIC_MAX_ACTIVE_AGENTS,
  EXPO_PUBLIC_SCRAPER_BASE_URL: process.env.EXPO_PUBLIC_SCRAPER_BASE_URL,
  EXPO_PUBLIC_SCRAPER_ENDPOINT: process.env.EXPO_PUBLIC_SCRAPER_ENDPOINT,
  EXPO_PUBLIC_SCRAPER_INTERVAL_HOURS: process.env.EXPO_PUBLIC_SCRAPER_INTERVAL_HOURS,
  EXPO_PUBLIC_ENABLE_AUTO_SCRAPER: process.env.EXPO_PUBLIC_ENABLE_AUTO_SCRAPER,
  EXPO_PUBLIC_REQUEST_TIMEOUT: process.env.EXPO_PUBLIC_REQUEST_TIMEOUT,
};
